// List of academic domains allowed for signup
export const ACADEMIC_DOMAINS = [
  'iiitg.ac.in',
  'iitb.ac.in',
  'iitd.ac.in',
  'iitk.ac.in',
  'iitm.ac.in',
  'iitkgp.ac.in',
  'iitg.ac.in',
  'iitr.ac.in',
  'iitbhu.ac.in',
  'iitgn.ac.in',
  'iith.ac.in',
  'iiti.ac.in',
  'iitj.ac.in',
  'iitmandi.ac.in',
  'iitp.ac.in',
  'iitpkd.ac.in',
  'iitrpr.ac.in',
  'iitt.ac.in',
  'iitbbs.ac.in',
  'iitbhilai.ac.in',
  'iitgoa.ac.in',
  'iitism.ac.in',
  'iitjammu.ac.in',
  'iitpalakkad.ac.in',
  'iitpatna.ac.in',
  'iittirupati.ac.in',
  'nit.ac.in',
  'nitrkl.ac.in',
  'nitk.ac.in',
  'nitt.edu',
  'nitw.ac.in',
  'nitc.ac.in',
  'nitdgp.ac.in',
  'nitjsr.ac.in',
  'nitkkr.ac.in',
  'nitm.ac.in',
  'nitmanipur.ac.in',
  'nitmz.ac.in',
  'nitnagaland.ac.in',
  'nitp.ac.in',
  'nitpy.ac.in',
  'nitr.ac.in',
  'nits.ac.in',
  'nitsri.ac.in',
  'nitsikkim.ac.in',
  'nitsurat.ac.in',
  'nittrkl.ac.in',
  'nituk.ac.in',
  'nitw.ac.in',
  'nitwarangal.ac.in',
  'iiit.ac.in',
  'iiita.ac.in',
  'iiitb.ac.in',
  'iiitd.ac.in',
  'iiitdm.ac.in',
  'iiitg.ac.in',
  'iiith.ac.in',
  'iiitk.ac.in',
  'iiitm.ac.in',
  'iiitp.ac.in',
  'iiitv.ac.in',
  'iiitvadodara.ac.in',
  'iiitvishakapatnam.ac.in',
  'iiitkota.ac.in',
  'iiitl.ac.in',
  'iiitn.ac.in',
  'iiitp.ac.in',
  'iiitranchi.ac.in',
  'iiits.ac.in',
  'iiitsonepat.ac.in',
  'iiitt.ac.in',
  'iiitu.ac.in',
  'iiitv.ac.in',
  'iiitvadodara.ac.in',
  'iiitvishakapatnam.ac.in',
]

/**
 * Check if an email domain is academic
 */
export function isAcademicEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return false
  
  return ACADEMIC_DOMAINS.some(academicDomain => 
    domain === academicDomain || domain.endsWith(`.${academicDomain}`)
  )
}

